@startuml
package presentation
{
    +class Main{
        +{static} main(args: String[])
    }
    ~class HomeView
    {

    }
    
    ~class LoginView
    {

    }
    ~class SetupView
    {
        
    }
    ~class ClosetView
    {
        
    }
    ~class PersonView
    {
        
    }
    ~class TryOnView
    {
        
    }
    ~class ClothesView
    {
        
    }
    ~class SuggestionView
    {
        
    }
    ~class PosesView
    {
        
    }
    ~class SettingView
    {
        
    }

}

package domain
{
    +class Closet
    {
        -clothes: List<Garment>
        -loader: GarmentDataLoader
        -saver: GarmentDataWriter
    }

    +class Garment
    {
        sn: SerialNumber

    }

    +class PoseCollection
    {
        -poses: List<Pose>
        -loader: PoseDataLoader
        -saver: PoseDataWriter
    }

    +class Pose{

    }
    +class AccountCollection
    {
        -accounts: List<Account>
        -loader: AccountDataLoader
        -saver: AccountDataWriter
    }
    +class Account
    {

    }
    
    +class SerialNumber
    {
        sn: String
    }

    +class GarmentSpec
    {

    }
    +class GarmentDataMapper
    {

    }
    +class PoseDataMapper
    {
        
    }
    +class AccountDataMapper
    {

    }
}

package datasource
{
    +abstract GarmentDataWriter
    {
        -observers: List<GarmentObserver>

        +GarmentDataWriter()
        +GarmentDataWriter(observers: List<GarmentObserver>)
        +subscribe(o: GarmentObserver): void
        +unsubscribe(o: GarmentObserver): void
        #updateAll(): void

        +{abstract} addGarment(GarmentDTO): void
        +{abstract} removeGarment(GarmentDTO): boolean
    }
    
    +abstract PoseDataWriter
    {
        -observers: List<PoseObserver>

        +PoseDataWriter()
        +PoseDataWriter(observers: List<PoseObserver>)
        +subscribe(o: PoseObserver): void
        +unsubscribe(o: PoseObserver): void
        #updateAll(): void

        +{abstract} addPose(PoseDTO): void
        +{abstract} removePose(PoseDTO): boolean
    }

    +abstract AccountDataWriter
    {
        -observers: List<AccountObserver>

        +AccountDataWriter()
        +AccountDataWriter(observers: List<AccountObserver>)
        +subscribe(o: AccountObserver): void
        +unsubscribe(o: AccountObserver): void
        #updateAll(): void

        +{abstract} addAccount(AccountDTO): void
        +{abstract} removeAccount(AccountDTO): boolean
    }

    +interface GarmentObserver
    {
        +{abstract}update(): void
    }
    +interface PoseObserver
    {
         +{abstract}update(): void
    }
    +interface AccountObserver
    {
        +{abstract}update(): void
    }

    +class DatabaseGarmentDataWriter
    {
        +addGarment(GarmentDTO): void
        +removeGarment(GarmentDTO): boolean
    }
    +class DatabasePoseDataWriter
    {
        +addPose(PoseDTO): void
        +removePose(PoseDTO): boolean
    }
    +class DatabaseAccountDataWriter
    {
        +addAccount(AccountDTO): void
        +removeAccount(AccountDTO): boolean
    }

    +class GarmentDTO
    {
        
    }
    +class PoseDTO
    {

    }
    +class AccountDTO
    {

    }
    +interface GarmentDataLoader
    {
        +{abstract} getNextGarment(): GarmentDTO
    }
    +interface PoseDataLoader
    {
        +{abstract} getNextPose(): PoseDTO
    }
    +interface AccountDataLoader
    {
        +{abstract} getNextAccount(): AccountDTO
    }
    +class DatabaseGarmentDataLoader
    {
        +getNextGarment(): GarmentDTO
    }
    +class DatabasePoseDataLoader
    {
        +getNextPose(): PoseDTO
    }
    +class DatabaseAccountDataLoader
    {
        +getNextAccount(): AccountDTO
    }

}

Main ..> HomeView
Main ..> LoginView
Main ..> GarmentDataWriter
Main ..> PoseDataWriter
Main ..> AccountDataWriter
Main ..> GarmentDataLoader
Main ..> PoseDataLoader
Main ..> AccountDataLoader
Main ..> DatabaseGarmentDataWriter
Main ..> DatabasePoseDataWriter
Main ..> DatabaseAccountDataWriter
Main ..> DatabaseGarmentDataLoader
Main ..> DatabasePoseDataLoader
Main ..> DatabaseAccountDataLoader

LoginView ..> SetupView
LoginView ..> HomeView
HomeView --> ClosetView
HomeView --> PersonView
HomeView ..> TryOnView
HomeView ..> SettingView
TryOnView --> ClothesView
TryOnView --> PersonView
TryOnView --> SuggestionView
TryOnView ..> PosesView


Closet -->"*" Garment
Closet --> GarmentDataWriter
Closet --> GarmentDataLoader
Closet ..> GarmentDataMapper
Closet ..> GarmentSpec
Closet ..> SerialNumber

PoseCollection -->"*" Pose
PoseCollection --> PoseDataWriter
PoseCollection --> PoseDataLoader
PoseCollection ..> PoseDataMapper

AccountCollection -->"*" Account
AccountCollection --> AccountDataWriter
AccountCollection --> AccountDataLoader
AccountCollection ..> AccountDataMapper

Garment --> GarmentSpec
Garment --> SerialNumber

GarmentDataWriter -->"*" GarmentObserver
PoseDataWriter -->"*" PoseObserver
AccountDataWriter -->"*" AccountObserver

Closet ..|> GarmentObserver
ClosetView ..|> GarmentObserver
ClothesView ..|> GarmentObserver
SuggestionView ..|> GarmentObserver

PoseCollection ..|> PoseObserver
PosesView ..|> PoseObserver

AccountCollection ..|> AccountObserver
LoginView ..|> AccountObserver
SettingView ..|> AccountObserver

GarmentDataWriter ..> GarmentDTO
GarmentDataMapper ..> GarmentDTO
GarmentDataLoader ..> GarmentDTO

PoseDataWriter ..> PoseDTO
PoseDataMapper ..> PoseDTO
PoseDataLoader ..> PoseDTO

AccountDataWriter ..> AccountDTO
AccountDataMapper ..> AccountDTO
AccountDataLoader ..> AccountDTO

DatabaseGarmentDataWriter --|> GarmentDataWriter
DatabasePoseDataWriter --|> PoseDataWriter
DatabaseAccountDataWriter --|> AccountDataWriter

DatabaseGarmentDataLoader ..|> GarmentDataLoader
DatabasePoseDataLoader ..|> PoseDataLoader
DatabaseAccountDataLoader ..> AccountDataLoader
@enduml
