@startuml
package presentation
{
    +class Main{
        +{static} main(args: String[])
    }
    ~class HomeView
    {

    }
    
    ~class LoginView
    {

    }
    ~class SetupView
    {
        
    }
    ~class ClosetView
    {
        
    }
    ~class PersonView
    {
        
    }
    ~class TryOnView
    {
        
    }
    ~class ClothesView
    {
        
    }
    ~class SuggestionView
    {
        
    }
    ~class PosesView
    {
        
    }
    ~class SettingView
    {
        
    }

}
Main ..> HomeView
Main ..> LoginView

LoginView ..> SetupView
HomeView --> ClosetView
HomeView --> PersonView
HomeView ..> TryOnView
HomeView ..> SettingView
TryOnView --> ClothesView
TryOnView --> PersonView
TryOnView --> SuggestionView
TryOnView ..> PosesView
package domain
{
    +class Closet
    {
        garments: List<Garment>
    }

    +class Garment
    {
        sn: SerialNumber

    }

    +class PoseCollection
    {

    }

    +class Pose{

    }
    +class AccountCollection
    {

    }
    +class Account
    {

    }
    
    +class SerialNumber
    {
        sn: String
    }

    +class GarmentSpec
    {

    }
    +class GarmentDataMapper
    {

    }
    +class PoseDataMapper
    {
        
    }
    +class AccountDataMapper
    {

    }
}

package datasource
{
    +abstract class GarmentDataWriter
    {
        observers: List<GarmentObserver>
    }
    
    +abstract class PoseDataWriter
    {
        observers: List<PoseObserver>
    }

    +abstract class AccountDataWriter
    {
        observers: List<AccountObserver>
    }

    +interface GarmentObserver
    {

    }
    +interface PoseObserver
    {
        
    }
    +interface AccountObserver
    {

    }

    +class DatabaseGarmentDataWriter
    {

    }
    +class DatabasePoseDataWriter
    {

    }
    +class DatabaseAccountDataWriter
    {

    }

    +class GarmentDTO
    {
        
    }
    +class PoseDTO
    {

    }
    +class AccountDTO
    {

    }
    +interface GarmentDataLoader
    {

    }
    +interface PoseDataLoader
    {

    }
    +interface AccountDataLoader
    {
        
    }
    +class DatabaseGarmentDataLoader
    {

    }
    +class DatabasePoseDataLoader
    {

    }
    +class DatabaseAccountDataLoader
    {

    }

}

GarmentDataWriter -->"*" GarmentObserver
PoseDataWriter -->"*" PoseObserver
AccountDataWriter -->"*" AccountObserver

Closet ..|> GarmentObserver
ClosetView ..|> GarmentObserver
ClothesView ..|> GarmentObserver
SuggestionView ..|> GarmentObserver

PoseCollection ..|> PoseObserver
PosesView ..|> PoseObserver

AccountCollection ..|> AccountObserver
LoginView ..|> AccountObserver
SettingView ..|> AccountObserver

GarmentDataWriter ..> GarmentDTO
GarmentDataMapper ..> GarmentDTO
GarmentDataLoader ..> GarmentDTO

PoseDataWriter ..> PoseDTO
PoseDataMapper ..> PoseDTO
PoseDataLoader ..> PoseDTO

AccountDataWriter ..> AccountDTO
AccountDataMapper ..> AccountDTO
AccountDataLoader ..> AccountDTO

DatabaseGarmentDataWriter --|> GarmentDataWriter
DatabasePoseDataWriter --|> PoseDataWriter
DatabaseAccountDataWriter --|> AccountDataWriter

DatabaseGarmentDataLoader ..|> GarmentDataLoader
DatabasePoseDataLoader ..|> PoseDataLoader
DatabaseAccountDataLoader ..> AccountDataLoader
@enduml
